version: '3.8'
services:
 movies:
   image: amitsathe/ptmmovies:v1
   ports:
     - "81:80"
   deploy:
   replicas: 3
 train:
     image: amitsathe/ptmtrain:v1
     ports:
       - "82:80"
     deploy:
       replicas: 3
 dth:
   image: amitsathe/ptmdth:v1
   ports:
     - "83:80"
   deploy:
     replicas: 3
